/*
 * This source file was generated by the Gradle 'init' task
 */
package jvm.daily

import ai.koog.agents.core.agent.AIAgent
import ai.koog.prompt.message.Message
import kotlinx.coroutines.runBlocking

class App {
    fun runSimpleAgent() = runBlocking {
        // This is a placeholder example showing Koog usage
        // In a real scenario, you'd provide an API key via environment variable
        // e.g., export OPENAI_API_KEY=your-key
        
        println("Initializing Koog Agent...")
        
        /* 
        val agent = AIAgent(
            systemPrompt = "You are a helpful assistant for JVM developers."
        )
        
        val response = agent.run("What's new in Java 23?")
        println("Agent response: $response")
        */
        
        println("Koog framework is successfully integrated!")
    }
}

fun main() {
    App().runSimpleAgent()
}
