rss:
  - url: "https://inside.java/feed.xml"
  - url: "https://spring.io/blog.atom"
  - url: "https://blog.jetbrains.com/kotlin/feed/"
  - url: "https://feeds.feedblitz.com/baeldung"
  - url: "https://feed.infoq.com/java"
  - url: "https://quarkus.io/feed.xml"
  - url: "https://micronaut.io/feed/"
  - url: "https://foojay.io/feed/"
  - url: "https://feed.gradle.org/blog.atom"
  - url: "https://blog.jetbrains.com/feed/"
  - url: "https://vladmihalcea.com/feed/"
  - url: "https://thorben-janssen.com/feed/"
  - url: "https://dev.to/feed/marcobehler"
  - url: "https://adambien.blog/roller/abien/feed/entries/atom"
  - url: "https://feeds.dzone.com/java"
  - url: "https://hnrss.org/newest?q=java+OR+kotlin+OR+jvm+OR+spring+OR+graalvm"
  - url: "https://medium.com/feed/graalvm"

reddit:
  - subreddit: "java"
  - subreddit: "Kotlin"
  - subreddit: "scala"
