export const scenes = [
  {
    id: 'overview',
    title: 'JVM Daily Overview',
    mode: 'default',
    voiceText: 'Welcome to JVM Daily — an automated news aggregator for the JVM ecosystem. Every morning, the pipeline collects articles from over a hundred sources including RSS feeds, Bluesky, Reddit, GitHub, and OpenJDK mailing lists.',
    captionText: 'JVM Daily — automated JVM ecosystem news aggregator.',
    estimatedDurationMs: 12_000,
  },
  {
    id: 'browse-digest',
    title: 'Browsing the Daily Digest',
    mode: 'default',
    voiceText: 'The digest view shows articles grouped into thematic clusters. Each cluster has an AI-generated synthesis summarizing the key points. You can browse different dates using the sidebar on the left.',
    captionText: 'Browsing thematic clusters with AI-generated synthesis.',
    estimatedDurationMs: 10_000,
  },
  {
    id: 'cluster-detail',
    title: 'Exploring a Cluster',
    mode: 'default',
    voiceText: 'Inside each cluster, individual articles are displayed with their source, summary, and topic tags. Bluesky posts sharing the same article are automatically merged — notice both handles shown at the bottom.',
    captionText: 'Cluster detail with merged Bluesky social cards.',
    estimatedDurationMs: 12_000,
  },
  {
    id: 'navigate-dates',
    title: 'Navigating Between Dates',
    mode: 'default',
    voiceText: 'The sidebar shows all available dates. Clicking a different date loads that day\'s digest instantly. The pipeline generates digests for the last 30 days of content.',
    captionText: 'Navigate between daily digests via the sidebar.',
    estimatedDurationMs: 10_000,
  },
  {
    id: 'rots-bookmarks',
    title: 'ROTS — Read On The Shitter',
    mode: 'default',
    voiceText: 'The ROTS feature lets you bookmark interesting clusters for later reading. Click the star icon on any cluster to add it to your reading list. Bookmarks are stored locally in your browser.',
    captionText: 'Bookmark clusters with the ROTS feature.',
    estimatedDurationMs: 10_000,
  },
  {
    id: 'pipeline-view',
    title: 'Pipeline Monitoring',
    mode: 'default',
    voiceText: 'The Pipeline tab shows the status of the automated ingestion pipeline — total successful runs, failures, and scheduled jobs. This runs daily at six AM, enriching articles with Gemini AI.',
    captionText: 'Monitor pipeline health and run history.',
    estimatedDurationMs: 8_000,
  },
]
